### ISSUE TITLE
`requeue_policy::deferred` is not thread safe

### ISSUE THREAD

**Issue by mjcaisse** [intel/cpp-baremetal-senders-and-receivers#38]
`std::exchange` is not atomic and a higher priority `enqueue_task` could be called mid-exchange, resulting in a torn data structure.

https://github.com/intel/cpp-baremetal-senders-and-receivers/blob/main/include/async/schedulers/task_manager.hpp#L30

**Comment by bdeane-intel** [comment]
Well spotted! The race is present with either enqueueing a task or cancelling a task.
