### ISSUE TITLE
Using start_on with fixed_priority_scheduler or timer_scheduler and start_detached crashes

### ISSUE THREAD

**Issue by Thurnheer** [intel/cpp-baremetal-senders-and-receivers#71]
It seems that the allocation is not persistent.

**Comment by elbeno** [comment]
@mjcaisse @mjcaisse-intel this could be affecting you

**Comment by Thurnheer** [comment]
Thank you for your fast reply and fix. This is an awesome library. And also thank you for the great work and effort you and your colleagues put into this.
